#!/bin/bash

APPLICATION_DIR=$HOME/Application
CONFIG_DIR=$APPLICATION_DIR/config
DOCKER_DIR=$APPLICATION_DIR/docker
MANAGEMENT_DIR=$APPLICATION_DIR/management
SECRETS_DIR=$APPLICATION_DIR/secrets
STACK_DIR=$APPLICATION_DIR/stack