#!/bin/bash

APPLICATION_DIR=$HOME/Application
DOCKER_DIR=$APPLICATION_DIR/docker
MANAGEMENT_DIR=$APPLICATION_DIR/management
SECRETS_DIR=$APPLICATION_DIR/secrets
STACK_DIR=$APPLICATION_DIR/stack
CONFIG_DIR=$STACK_DIR/config
