spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: fill_at_server
    url: jdbc:postgresql://localhost:5432/accountant
    username: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  ssl:
    key-store: "/home/slag/sg-application/certs/sgapplication.p12"
    key-store-password: "fill_at_server"
    key-store-type: pkcs12
    key-alias: sg-application
    key-password: "fill_at_server"
  port: 8443