version: '3.8'

services:

  app:
    image: 215372400964.dkr.ecr.eu-central-1.amazonaws.com/backend:latest
    container_name: backend
    ports:
      - "8090:8443"
    environment:
      spring_profiles_active: https
    configs:
      - source: application.yml
        target: /app/application.yml
    secrets:
      - jwt_secret_code
      - sendgrid_api_key
      - sgapplication.p12
      - nordigen_secret_id
      - nordigen_secret_key
      - postgres_password
      - key_store_password
      - key_password
      - aws_access_key_id
      - aws_secret_access_key
      - aws_region
    volumes:
      - $HOME/docker/volumes/logs:/app/logs/

  client:
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: app
        awslogs-stream: client
        awslogs-create-group: 'true'
    image: 215372400964.dkr.ecr.eu-central-1.amazonaws.com/client:latest
    container_name: client
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - sgapplication.crt
      - sgapplication.key
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: app
        awslogs-stream: db
        awslogs-create-group: 'true'
    image: postgres:14.5
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
        - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
        
configs:
  application.yml:
    template_driver: golang
    file: application.yml.tmpl
    name: myapp.application.yml${APPLICATION_YML_VERSION:-0}
    
secrets:
  jwt_secret_code:
    external: true
  sendgrid_api_key:
    external: true
  nordigen_secret_id:
    external: true
  nordigen_secret_key:
    external: true
  postgres_password:
    external: true
  key_store_password:
    external: true
  key_password:
    external: true
  sgapplication.crt: 
    file: certs/sgapplication.crt
  sgapplication.key: 
    file: certs/sgapplication.key
  sgapplication.p12: 
    file: certs/sgapplication.p12
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true
  aws_region:
    external: true
  