version: '3.8'

services:

  db:
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: /app
        awslogs-stream: db
        awslogs-create-group: 'true'
    image: postgres:14.5
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
        - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    
secrets:
  postgres_password:
    external: true
  