version: '3.8'

services:

  registry:
    image: registry:2.8.3
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - $HOME/Artifacts:/var/lib/registry
      - $HOME/Artifacts/auth:/auth
    secrets:
      - sgapplication.crt
      - sgapplication.key
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/sgapplication.crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/sgapplication.key
    restart: always

secrets:
  sgapplication.crt:
    file: $HOME/Application/secrets/certs/sgapplication.crt
  sgapplication.key:
    file: $HOME/Application/secrets/certs/sgapplication.key