spring:
  datasource:
    hikari:
      connectionTimeout: 15000
      maximumPoolSize: 5
    password: SLAwek1!
    url: jdbc:postgresql://localhost:5432/accountant
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 30MB
  main:
    banner-mode: off
  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher

nodrigen:
  service-url: https://ob.nordigen.com/api/v2/

cron:
  fetch-accounts: "-"
  fetch-accounts-monthly: "-"
  fetch-transactions: "-"

intellectual-property:
  task:
    attachments:
      storage:
        dir: D:\\Development\\S3cpy