intellectual-property:
  task:
    attachments:
      storage:
        dir: "F:\\OneDrive\\Dokumenty\\SG\ app\ backup\\S3cpy"

pjm:
  videos-location: "F:\\Development\\bibleFiles"

nodrigen:
  log:
    requests:
      dir: "F:\\Development\\nodrigen_requests"