spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: SLAwek1!
    url: jdbc:postgresql://localhost:5432/accountant
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    banner-mode: off
  sql:
    init:
      mode: always
nodrigen:
  service-url: https://ob.nordigen.com/api/v2/

cron:
  fetch-accounts: "-"
  fetch-accounts-monthly: "-"
  fetch-transactions: "-"