intellectual-property:
  task:
    attachments:
      storage:
        dir: ${HOME}/Development/Slawek/files/S3cpy

pjm:
  videos-location: ${HOME}/Development/Slawek/files/bibleFiles

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/accountant

nodrigen:
  log:
    requests:
      dir: ${HOME}/Development/Slawek/files/nodrigen_requests