spring:
  datasource:
    hikari:
      connectionTimeout: 15000
      maximumPoolSize: 5
    password: SLAwek1!
#    url: jdbc:postgresql://localhost:5432/accountant
    url: jdbc:postgresql://192.168.52.169:5432/accountant
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jooq:
    sql-dialect: POSTGRES
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 30MB
  main:
    banner-mode: off
  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher

nodrigen:
  service-url: https://ob.nordigen.com/api/v2/

random-org:
  url: https://api.random.org/json-rpc/4/invoke

cron:
  fetch-accounts: "-"
  fetch-accounts-monthly: "-"
  fetch-transactions: "-"