spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: SLAwek1!
    url: jdbc:postgresql://192.168.52.98:5432/accountant
    username: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
nodrigen:
  service-url: https://ob.nordigen.com/api/v2/