version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
      - image: postgres
        environment:
          POSTGRES_PASSWORD: slawek
    working_directory: ~/accountent
    steps:
      - checkout
      - run: pwd
      - run: ls -al
      - run: "sed -i 's/url: .*192\\.168\\.99\\.100:32768\\/postgres/url: jdbc:postgresql:\\/\\/localhost:5432\\/postgres/' src/integrationTest/resources/application-it.yml"
      - run: cat src/integrationTest/resources/application-it.yml
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: gradle clean build runIntegrationTest