version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "build.gradle.kts" }}
                  - v1-dependencies-
            - run: gradle dependencies
            - save_cache:
                paths:
                  - ~/.m2
                key: v1-dependencies-{{ checksum "build.gradle.kts" }}
            - run: gradle clean build
            - setup_remote_docker
            - aws-ecr/build-and-push-image:
                repo: 'backend'
                tag: latest-rpi4
                assume-web-identity: false
                attach-workspace: false
                create-repo: false
                docker-login: false
                public-registry: false
                push-image: true
                remote-docker-layer-caching: false
                repo-scan-on-push: true
                setup-remote-docker: false
                skip-when-tags-exist: false
                dockerfile: docker/production_home/Dockerfile
                platform: linux/arm64
                region: eu-central-1
            - run:
                name: remove existing Docker context
                command: docker context rm -f builder
            - aws-ecr/build-and-push-image:
                repo: 'backend'
                tag: latest-debug-rpi4
                assume-web-identity: false
                attach-workspace: false
                create-repo: false
                docker-login: false
                public-registry: false
                push-image: true
                remote-docker-layer-caching: false
                repo-scan-on-push: true
                setup-remote-docker: false
                skip-when-tags-exist: false
                dockerfile: docker/production_home/Dockerfile-debug
                platform: linux/arm64
                region: eu-central-1
            - run: scp -o "StrictHostKeyChecking no" build/distributions/dockerRpi4.zip $SSH_USER@$SSH_HOST:/home/slawek/Application
            - run: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "cd /home/slawek/Application && unzip dockerRpi4.zip -d tmp && cd tmp/setup && dos2unix deploy_files.sh && chmod +x deploy_files.sh && ./deploy_files.sh"
            - run: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "cd /home/slawek/Application/management && ./start.sh"

workflows:
  workflow:
    jobs:
      - build