version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.4
    steps:
      - run: ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "ls /home/slawek"

workflows:
  workflow:
    jobs:
      - build