version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.4
    steps:
      - checkout
      - run: gradle clean build
      - run: docker --help
      - aws-ecr/build-and-push-image:
          repo: 'dkr.ecr.eu-central-1.amazonaws.com' 
          assume-web-identity: false 
          attach-workspace: false 
          create-repo: false 
          docker-login: false 
          public-registry: false 
          push-image: true 
          remote-docker-layer-caching: false 
          repo-scan-on-push: true 
          setup-remote-docker: false 
          skip-when-tags-exist: false 
          dockerfile: docker/production/Dockerfile 
          platform: linux/amd64 
          region: eu-central-1

workflows:
  workflow:
    jobs:
      - build