spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: slawek
    url: jdbc:postgresql://localhost:5432/accountant1
    username: slawek
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
nodrigen:
  service-url: ""
cron:
  fetch-accounts: "-"
  fetch-accounts-monthly: "-"
  fetch-transactions: "-"