spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: slawek
        url: jdbc:postgresql://192.168.99.100:32768/postgres
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
