version: '3.8'

services:
  db:
    build: ./database
    image: accountant-db:1.0.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: SLAwek1!
    container_name: accountant-db
  app:
    build: .
    image: accountant-backend:1.0.0
    container_name: accountant-backend
    ports:
      - "8080:8080"
    environment:
      JWT_TOKEN: dupa

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pi/postgres