version: '3.8'

services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=SLAwek1!
    volumes:
      - D:\Development\docker_volumes:/var/lib/postgresql/data