version: '3.8'

services:

  app:
    build: ./backend
    image: accountant-backend:1.0.0
    container_name: accountant-backend
    ports:
      - "8080:8080"
    environment:
      JWT_TOKEN: JWT_TOKEN
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  client:
    build: ./client
    image: accountant-client:1.0.0
    restart: always
    ports:
      - "80:80"
    container_name: accountant-client
    networks:
      app_net:
        ipv4_address: 172.16.238.12

networks:
  app_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1