version: '3'
services:
  postgres:
    image: postgres
    hostname: accountant-tests-postgres
    environment:
      POSTGRES_PASSWORD: slawek
    ports:
      - "32768:5432"
    volumes:
      - /c/Users/qvc843/accountant-pg-tests:/var/lib/postgresql/data