name: build app

on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: setup insecure registry
        id: setup-insecure-registry
        run: |
          echo { | sudo tee /etc/docker/daemon.json
          echo "\"insecure-registries\" : [\"https://grzegorzewski.org:5005\"]" | sudo tee -a /etc/docker/daemon.json
          echo } | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: run postgres
        id: run-postgres
        run: |
          docker run -e POSTGRES_PASSWORD=postgres --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 -p 5432:5432 -d --name postgres postgres:15.6
          docker ps

      - name: Login to Registry
        id: login-to-registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SG_REGISTRY_URL }}
          username: ${{ secrets.SG_REGISTRY_USER }}
          password: ${{ secrets.SG_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v3

      - name: prepare db
        run: docker exec $(docker ps -f name=postgres --quiet) psql -h localhost -p 5432 -U postgres -w postgres -c 'CREATE DATABASE accountant;'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName

      - name: Build with Gradle Wrapper
        id: build
        run: |
           ./gradlew migrate build infrastructureRpi4
        env:
          SG_DB_URL: "jdbc:postgresql://localhost:5432/accountant"
          SG_DB_PASSWORD: postgres

      - name: Build with Gradle Wrapper
        run: ./gradlew migrate
        env:
          SG_DB_URL: ${{ secrets.SG_DB_URL }}
          SG_DB_PASSWORD: ${{ secrets.SG_DB_PASSWORD }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        env:
          REGISTRY: ${{ secrets.SG_REGISTRY_URL }}
          REPOSITORY: backend
        run: |
          export BUILD_DATE=$(date +'%Y-%m-%d_%H-%M')
          docker buildx build . -f dev-ops/apps/sg-application/Dockerfile -t $REGISTRY/$REPOSITORY:latest -t $REGISTRY/$REPOSITORY:$BUILD_DATE-$(git rev-parse --short "$GITHUB_SHA") --platform linux/arm64 --push
          docker buildx build . -f dev-ops/apps/sg-application//Dockerfile-debug -t $REGISTRY/$REPOSITORY:latest-debug -t $REGISTRY/$REPOSITORY:$BUILD_DATE-$(git rev-parse --short "$GITHUB_SHA")-debug --platform linux/arm64 --push