name: build app

on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Login to Registry
        id: login-to-registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SG_REGISTRY_URL }}
          username: ${{ secrets.SG_REGISTRY_USER }}
          password: ${{ secrets.SG_REGISTRY_PASSWORD }}