name: update configuration

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName

      - name: Build with Gradle Wrapper
        id: build
        run: |
           ./gradlew dockerPackageRpi4
          mv build/distributions/dockerRpi4.zip .

      - name: copy dockerRpi4.zip via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: dockerRpi4.zip
          target: /home/${{ secrets.SSH_USER }}/Application

      - name: unpack and deploy application files
        uses: appleboy/ssh-action@master
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}/Application
            unzip dockerRpi4.zip -d tmp
            cd tmp/setup && dos2unix setup_directories.sh deploy_files.sh
            chmod +x setup_directories.sh deploy_files.sh
            ./deploy_files.sh
            cd /home/${{ secrets.SSH_USER }}/Application/management
            ./stop.sh && sleep 5 && ./start.sh
