name: build app

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Login to Registry
        id: login-to-registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SG_REGISTRY_URL }}
          username: ${{ secrets.SG_REGISTRY_USER }}
          password: ${{ secrets.SG_REGISTRY_PASSWORD }}

      - name: Deploy the latest backend
        id: deploy_latest_backend
        uses: appleboy/ssh-action@master
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          REGISTRY: ${{ secrets.SG_REGISTRY_URL }}
          REPOSITORY: backend
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker service update --force --image ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest application_backend